### PR TITLE
Display pagination on page count > 1

### PR DESCRIPTION
**Pull request by yen-tt**
don't display pagination component on page load or page count of 1

J=SLAP-1806
TEST=manual

load page with 1 result page, see that pagination didn't get display

### CODE REVIEW

**Review by cea2aj — APPROVED** [review]

**Comment by cea2aj** [comment]
I know I approved this, but we may want to coordinate with Tom if any other changes are going into v1.0.1

**Comment by tmeyer2115** [comment]
> I know I approved this, but we may want to coordinate with Tom if any other changes are going into v1.0.1

I'll mention this in Standup today, but I've made a v1.0.1 version in Jira. It will include this fix as well as the Applied Filters item Nidhi is working on.

**Comment by oshi97** [comment]
I think we want to merge this branch into the hotfix branch, instead of having this branch be the hotfix branch?

**Comment by yen-tt** [comment]
> I think we want to merge this branch into the hotfix branch, instead of having this branch **be** the hotfix branch?

yea

**Pull request closed without merging**
